name: Fetch Electron
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-electron-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Download Electron
        env:
          DOM: "github.com"
          REP: "electron/electron"
          TAG: "v42.2.0"
        run: |
          curl -L -o electron-latest-win32-x64.zip https://$DOM/$REP/releases/download/$TAG/electron-$TAG-win32-x64.zip
      
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "latest-stable"
          name: "Electron"
          body: ""
          files: "electron-latest-win32-x64.zip"
          draft: false
          prerelease: false
